"""create trigger replies

Revision ID: b7f562417066
Revises: 0001_init_user_tags
Create Date: 2025-12-18 14:34:14.305560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7f562417066'
down_revision = '0001_init_user_tags'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_replies_keyword'), 'trigger_replies', ['keyword'], unique=True)
    op.alter_column('tg_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tg_user_tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('fk_tg_user_tag_referral_tag_id', 'tg_user_tag', type_='foreignkey')
    op.drop_constraint('fk_tg_user_tag_tg_user_id', 'tg_user_tag', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_tag', 'referral_tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'tg_user_tag', 'tg_user', ['tg_user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_user_tag', type_='foreignkey')
    op.drop_constraint(None, 'tg_user_tag', type_='foreignkey')
    op.create_foreign_key('fk_tg_user_tag_tg_user_id', 'tg_user_tag', 'tg_user', ['tg_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_tg_user_tag_referral_tag_id', 'tg_user_tag', 'referral_tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tg_user_tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tg_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_trigger_replies_keyword'), table_name='trigger_replies')
    op.drop_table('trigger_replies')
    # ### end Alembic commands ###
